// This file is auto-generated by @hey-api/openapi-ts

export type AssessmentCreate = {
    question_text: string;
    question_type?: string;
    points?: number;
    answer_text?: (string | null);
    hint_text?: (string | null);
    flag_format?: (string | null);
    difficulty?: string;
    is_active?: boolean;
    challenge_id: string;
};

export type AssessmentPublic = {
    question_text: string;
    question_type?: string;
    points?: number;
    answer_text?: (string | null);
    hint_text?: (string | null);
    flag_format?: (string | null);
    difficulty?: string;
    is_active?: boolean;
    id: string;
    challenge_id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
    challenge?: (Challenge | null);
};

export type AssessmentsPublic = {
    data: Array<AssessmentPublic>;
    count: number;
};

export type AssessmentUpdate = {
    question_text?: (string | null);
    question_type?: (string | null);
    points?: (number | null);
    answer_text?: (string | null);
    hint_text?: (string | null);
    flag_format?: (string | null);
    difficulty?: (string | null);
    is_active?: (boolean | null);
    challenge_id?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Challenge = {
    title: string;
    author: string;
    url: string;
    description: string;
    date_posted: string;
    is_active?: boolean;
    id?: string;
    owner_id: string;
};

export type ChallengeCreate = {
    title: string;
    author: string;
    url: string;
    description: string;
    date_posted: string;
    is_active?: boolean;
};

export type ChallengePublic = {
    title: string;
    author: string;
    url: string;
    description: string;
    date_posted: string;
    is_active?: boolean;
    id: string;
    owner_id: string;
};

export type ChallengesPublic = {
    data: Array<ChallengePublic>;
    count: number;
};

export type ChallengeUpdate = {
    title?: (string | null);
    author?: (string | null);
    url?: (string | null);
    description?: (string | null);
    date_posted?: (string | null);
    is_active?: (boolean | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type QuestionCreate = {
    type?: string;
    step?: (number | null);
    subject: string;
    description: string;
    more_info: string;
    challenge_id: string;
};

export type QuestionPublic = {
    type?: string;
    step?: (number | null);
    subject: string;
    description: string;
    more_info: string;
    id: string;
    challenge_id: string;
    asked_by: (string | null);
    asked_time: string;
    assigned_to: (string | null);
    answered_time: (string | null);
};

export type QuestionsPublic = {
    data: Array<QuestionPublic>;
    count: number;
};

export type QuestionUpdate = {
    type?: (string | null);
    step?: (number | null);
    subject?: (string | null);
    description?: (string | null);
    more_info?: (string | null);
    challenge_id?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserRole = 'student' | 'proctor' | 'lecturer' | 'admin';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AssessmentsReadAssessmentsData = {
    challengeId?: (string | null);
    limit?: number;
    skip?: number;
};

export type AssessmentsReadAssessmentsResponse = (AssessmentsPublic);

export type AssessmentsCreateAssessmentData = {
    requestBody: AssessmentCreate;
};

export type AssessmentsCreateAssessmentResponse = (AssessmentPublic);

export type AssessmentsReadAssessmentData = {
    id: string;
};

export type AssessmentsReadAssessmentResponse = (AssessmentPublic);

export type AssessmentsUpdateAssessmentData = {
    id: string;
    requestBody: AssessmentUpdate;
};

export type AssessmentsUpdateAssessmentResponse = (AssessmentPublic);

export type AssessmentsDeleteAssessmentData = {
    id: string;
};

export type AssessmentsDeleteAssessmentResponse = (Message);

export type AssessmentsGetAssessmentHintData = {
    id: string;
};

export type AssessmentsGetAssessmentHintResponse = ({
    [key: string]: unknown;
});

export type ChallengesReadChallengesData = {
    limit?: number;
    skip?: number;
};

export type ChallengesReadChallengesResponse = (ChallengesPublic);

export type ChallengesCreateChallengeData = {
    requestBody: ChallengeCreate;
};

export type ChallengesCreateChallengeResponse = (ChallengePublic);

export type ChallengesUpdateChallengeData = {
    id: string;
    requestBody: ChallengeUpdate;
};

export type ChallengesUpdateChallengeResponse = (ChallengePublic);

export type ChallengesReadChallengeData = {
    id: string;
};

export type ChallengesReadChallengeResponse = (ChallengePublic);

export type ChallengesDeleteChallengeData = {
    id: string;
};

export type ChallengesDeleteChallengeResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type QuestionsReadQuestionsData = {
    challengeId?: string;
    limit?: number;
    skip?: number;
};

export type QuestionsReadQuestionsResponse = (QuestionsPublic);

export type QuestionsCreateQuestionData = {
    requestBody: QuestionCreate;
};

export type QuestionsCreateQuestionResponse = (QuestionPublic);

export type QuestionsUpdateQuestionData = {
    id: string;
    requestBody: QuestionUpdate;
};

export type QuestionsUpdateQuestionResponse = (QuestionPublic);

export type QuestionsReadQuestionData = {
    id: string;
};

export type QuestionsReadQuestionResponse = (QuestionPublic);

export type QuestionsDeleteQuestionData = {
    id: string;
};

export type QuestionsDeleteQuestionResponse = (unknown);

export type QuestionsAssignQuestionData = {
    assignedTo: string;
    id: string;
};

export type QuestionsAssignQuestionResponse = (QuestionPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);