"""Add Challenge, Question, and FAQ models

Revision ID: 2a41df608447
Revises: 1a31ce608336
Create Date: 2025-01-31 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a41df608447'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create challenge table
    op.create_table('challenge',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('date_posted', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_challenge_id'), 'challenge', ['id'], unique=False)
    op.create_index(op.f('ix_challenge_title'), 'challenge', ['title'], unique=False)

    # Create question table
    op.create_table('question',
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('more_info', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('asked_by', sa.UUID(), nullable=True),
    sa.Column('asked_time', sa.DateTime(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('answered_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asked_by'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_id'), 'question', ['id'], unique=False)

    # Create faq table
    op.create_table('faq',
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('more_info', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_id'), 'faq', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faq_id'), table_name='faq')
    op.drop_table('faq')
    op.drop_index(op.f('ix_question_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_challenge_title'), table_name='challenge')
    op.drop_index(op.f('ix_challenge_id'), table_name='challenge')
    op.drop_table('challenge')
    # ### end Alembic commands ###