"""Add Assessment model and user roles

Revision ID: 3ec1328d7996
Revises: 2a41df608447
Create Date: 2025-08-01 11:42:41.556097

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3ec1328d7996'
down_revision = '2a41df608447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the UserRole enum type
    user_role_enum = sa.Enum('STUDENT', 'PROCTOR', 'LECTURER', 'ADMIN', name='userrole', create_type=False)
    user_role_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('assessment',
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('question_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('answer_text', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('hint_text', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('flag_format', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('challenge_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('challenge_title_key', 'challenge', type_='unique')
    op.drop_index('ix_challenge_id', table_name='challenge')
    op.drop_index('ix_challenge_title', table_name='challenge')
    op.create_index(op.f('ix_challenge_title'), 'challenge', ['title'], unique=True)
    op.drop_index('ix_faq_id', table_name='faq')
    op.drop_index('ix_question_id', table_name='question')
    op.drop_constraint('question_asked_by_fkey', 'question', type_='foreignkey')
    op.drop_constraint('question_assigned_to_fkey', 'question', type_='foreignkey')
    op.create_foreign_key(None, 'question', 'user', ['assigned_to'], ['id'])
    op.create_foreign_key(None, 'question', 'user', ['asked_by'], ['id'])
    # Add role column as nullable first
    op.add_column('user', sa.Column('role', sa.Enum('STUDENT', 'PROCTOR', 'LECTURER', 'ADMIN', name='userrole'), nullable=True))
    # Set default role for existing users (superusers become ADMIN, others become STUDENT)
    op.execute("UPDATE \"user\" SET role = CASE WHEN is_superuser = true THEN 'ADMIN'::userrole ELSE 'STUDENT'::userrole END")
    # Now make the column not nullable
    op.alter_column('user', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # Drop the UserRole enum type
    user_role_enum = sa.Enum('STUDENT', 'PROCTOR', 'LECTURER', 'ADMIN', name='userrole')
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.create_foreign_key('question_assigned_to_fkey', 'question', 'user', ['assigned_to'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('question_asked_by_fkey', 'question', 'user', ['asked_by'], ['id'], ondelete='CASCADE')
    op.create_index('ix_question_id', 'question', ['id'], unique=False)
    op.create_index('ix_faq_id', 'faq', ['id'], unique=False)
    op.drop_index(op.f('ix_challenge_title'), table_name='challenge')
    op.create_index('ix_challenge_title', 'challenge', ['title'], unique=False)
    op.create_index('ix_challenge_id', 'challenge', ['id'], unique=False)
    op.create_unique_constraint('challenge_title_key', 'challenge', ['title'])
    op.drop_table('assessment')
    # ### end Alembic commands ###
